#!/bin/bash

shell=unknown
sourced=false
current_dir=

if [[ -n $BASH_VERSION ]]; then
  if [[ "${BASH_SOURCE}" != "$0" ]]; then
    sourced=true
  fi
  shell="bash"
elif [[ -n $ZSH_VERSION ]]; then
  if [[ "${(%):-%x} != "$0"" ]]; then
    sourced=true
  fi
  shell="zsh"
  echo "WARNING: This was made for bash."
  echo "  Some things may not work."
else
  echo "WARNING: Unknown shell. This was made for bash."
  echo "  It may not work for your shell."
fi

# command line switch defaults
write=true
ps1hack=false

function _help() {
  echo "Usage: asdf [OPTION]"
  echo "Fast and flexible history searching and exploring."
  echo "Type a command to search your history for it."
  echo "Spaces allow you to search for multiple strings at the same time."
  echo ""
  echo "Controls:"
  echo "  Press Enter to run the command, or ^Space to edit the command and then run it."
  echo "  ^Del to remove the selected command from your HISTFILE."
  echo "  ^C to exit at any time without running anything."
  echo ""
  echo "Available options:"
  echo "  --write:[true|false]    Whether to write to HISTFILE when running a command."
  echo "                            Default:true"
  echo "  --ps1hack:[true|false]  Whether to try to show the PS1 when editing a command."
  echo "                            Default:false"
  echo "  --help                  Print this help text and exit."
}

function _asdf_main() {
  results=`HISTFILE="$HISTFILE" ${current_dir}/asdf_search.exe`
  asdf_status=$?
  if [ $asdf_status -ge 10 ]; then
    to_run=$results
    if [ $asdf_status -eq 11 ]; then
      if [[ $ps1hack == true ]]; then
        # hack to render a user's PS1
        expPS1=$(echo "HISTFILE=/dev/null PS1=\"$PS1@\" && cd `pwd`" | bash -i 2>&1 | grep "@exit$" | head -n 1 | sed 's/\(.*\)@exit$/\1/')
        read -e -p "$expPS1" -i "$results" to_run
      else
        read -e -i "$results" to_run
      fi
    fi
    if [[ "$to_run" != "" && "$to_run" ]]; then
      if [ $asdf_status -ne 11 ]; then
        echo "$to_run"
      fi
      if [[ $write == true ]]; then
        if [[ $shell == "bash" ]]; then
          history -s "$to_run"
        elif [[ $shell == "zsh" ]]; then
          print -S "$to_run"
        fi
      fi
      eval $to_run
    fi
  fi
}

if [[ $sourced == true ]]; then
  if [[ "$shell" =~ "bash" ]]; then
    current_dir=`dirname ${BASH_SOURCE}`
  elif [[ "$shell" =~ "zsh" ]]; then
    current_dir=`dirname ${(%):-%x}`
  fi
else
  echo "WARNING: It seems like this is running as a script."
  echo "  Some commands (like cd), and features (like adding to HISTFILE) won't work."
  echo "  Source this script instead of just running it to resolve these issues."
  current_dir=`dirname $0`
fi

runasdf=true

# process arguments
while [ "$1" != "" ]; do
  case $1 in
  --help*)
    _help
    runasdf=false
    ;;
  --write:*)
    write=`echo $1 | sed 's/^--[^:]*:\(.*\)$/\1/'`
    ;;
  --ps1hack:*)
    ps1hack=`echo $1 | sed 's/^--[^:]*:\(.*\)$/\1/'`
    ;;
  *)
    echo "Unknown argument, printing helptext and exiting..."
    _help
    runasdf=false
  esac
  shift
done

if [[ $runasdf == true ]]; then
  _asdf_main
fi
