#!/bin/bash
tmp=$(mktemp)
${BASH_SOURCE}_search.exe "$tmp"
asdf_status=$?
results=$(cat $tmp)
rm $tmp
if [ $asdf_status -ge 10 ]; then
  to_run=$results
  if [ $asdf_status -eq 11 ]; then
    read -e -i "$results" to_run
  fi
  if [[ "$to_run" != "" && "$to_run" ]]; then
    eval $to_run
    if [[ "$to_run" != "asdf" ]]; then
      echo "$to_run" >> $HISTFILE
    fi
  fi
fi
